// cfdf7238ad58710492dc79998bb70ddbf3200945
#pragma once

#include <ecs/systems/IUpdateSystem.hpp>
#include <ecs/systems/PositionUpdateSystem.hpp>
#include <ecs/systems/WayfindSystem.hpp>
#include <ecs/systems/TextEventSystem.hpp>
#include <ecs/systems/PressAwaySystem.hpp>
#include <ecs/systems/DespawnSystem.hpp>
#include <ecs/systems/IRenderSystem.hpp>
#include <ecs/systems/PrimitiveRenderSystem.hpp>
#include <ecs/systems/DecalRenderSystem.hpp>
#include <ecs/systems/AudioSystem.hpp>
#include <ecs/systems/TerrainRenderSystem.hpp>
#include <ecs/systems/LogSystem.hpp>
#include <ecs/systems/GravitySystem.hpp>
#include <ecs/systems/RandomJumpSystem.hpp>
#include <ecs/systems/BillboardRenderSystem.hpp>
#include <ecs/systems/TerrainCollisionSystem.hpp>
#include <ecs/systems/CharacterControllerSystem.hpp>
#include <ecs/systems/CHealthbarRenderSystem.hpp>
