name: Build Project

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  # TODO: Unused, See "Configure CMake"
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: |
          sudo apt update
          # TODO: Don't install `libluajit-5.1-dev`. VCPKG / Cmake should handle this.
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libgl1-mesa-dev libluajit-5.1-dev

      - name: Install Dependencies
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: 'cef0b3ec767df6e83806899fe9525f6cf8d7bc91'
          runVcpkgInstall: true

      - name: DEBUG Show vcpkg
        run: ls vcpkg_installed/**

      - name: Configure CMake
        run: cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: make
      
      - name: Create Archive
        run: tar -zcf bin/Release.tar.gz res/ -C bin/ synthlike

      - name: Push Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./bin/Release.tar.gz

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        uses: microsoft/setup-msbuild@v1.1

      - name: Install Dependencies
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: 'cef0b3ec767df6e83806899fe9525f6cf8d7bc91'
          runVcpkgInstall: true

      - name: Configure CMake
        run: cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: msbuild synthlike.sln

      - name: Create Archive
        # TODO: synthlike.sln is just for testing
        run: powershell Compress-Archive res/ synthlike.sln bin/Release.zip

      - name: Push Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./bin/Release.zip

