name: LinuxBuild

on: [push]
  #  push:
  #    branch:
  #      - 'develop'
  #    tags:
  #      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls ${{ github.workspace }}
      - name: Install Dependencies
        uses: lukka/run-vcpkg@v10
        with:
          runVcpkgFormatString: '[`install`, `glfw3`, `assimp`, `entt`, `openal-soft`, `lua`, `freetype`, `enet`, `fmt`, `--recurse`, `--clean-after-build`, `--x-install-root`, `$[env.VCPKG_INSTALLED_DIR]`, `--triplet`, `$[env.VCPKG_DEFAULT_TRIPLET]`]'
          vcpkgGitCommitId: 'cef0b3ec767df6e83806899fe9525f6cf8d7bc91'
      - run: ls ${{ github.workspace }}/vcpkg/
      - run: ls ${{ github.workspace }}/vcpkg/**
      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: cmake -DCMAKE_BUILD_TYPE=Release
      - name: Build
        # Build your program with the given configuration
        working-directory: ${{github.workspace}}
        run: make

