name: LinuxBuild

on: [push]
  #  push:
  #    branch:
  #      - 'develop'
  #    tags:
  #      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls ${{ github.workspace }}
      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: cmake -DCMAKE_BUILD_TYPE=Release
      - name: Build
        # Build your program with the given configuration
        working-directory: ${{github.workspace}}
        run: make

